[[news]]
date = "2025-10"
content = "Joined Yale University as a Postdoctoral Associate in the Department of Statistics and Data Science."

[[news]]
date = "2025-01"
content = "Our paper on SIMO for spatial integration of multi-omics single-cell data is published in *Nature Communications*."

[[news]]
date = "2024-12"
content = "Joined University of Michigan as a Postdoctoral Associate in the Department of Computational Medicine and Bioinformatics."

[[news]]
date = "2023-11"
content = "Our paper on SpaTrio for revealing spatial multimodal heterogeneity in tissues is published in *Cell Genomics*."
